name: Node.js CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Шаг клонирования репозитория

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Устанавливаем Node.js
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Установка зависимостей через package.json в корне

      - name: Run tests
        run: npm test  # Запуск тестов

      - name: Commit changes
        run: |
          git config --global user.name 'Roma'
          git config --global user.email 'batanov.ramazan05@gmail.com'
          git commit -m "Auto-commit from GitHub Actions" || echo "Nothing to commit"
