name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2
  - name: Set working directory
    run: cd path/to/your/project
  - name: Install dependencies
    run: npm install

